version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app

  fastapi:
    container_name: app_fastapi
    restart: unless-stopped
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    networks:
      - app

networks:
  app:
    driver: bridge